EXPORT_FOLDER_PROP = "export_folder"
EXPORT_INDIVIDUAL_PROP = "export_individual"
EXPORT_FBX_MODE_PROP = "export_fbx_mode"
EXPORT_RESET_LOCATION_PROP = "export_reset_location"
SELECT_BY_NAME_QUERY_PROP = "select_by_name_query"
SELECT_BY_NAME_EXACT_PROP = "select_by_name_exact"
